#!/bin/sh

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
APP_ROOT="$SCRIPT_DIR"

export NEXTREADING_HOME="${NEXTREADING_HOME:-$APP_ROOT}"
export NEXTUI_PAK_ROOT="${NEXTUI_PAK_ROOT:-$APP_ROOT}"
export NEXTREADING_BOOKS_PATH="${NEXTREADING_BOOKS_PATH:-$APP_ROOT/Books}"
export NEXTREADING_CACHE_PATH="${NEXTREADING_CACHE_PATH:-$APP_ROOT/BooksCache}"
export NEXTREADING_SAVES_PATH="${NEXTREADING_SAVES_PATH:-$APP_ROOT/Saves/RetroRead}"
export NEXTREADING_ASSETS_PATH="${NEXTREADING_ASSETS_PATH:-$APP_ROOT/assets}"
export NEXTUI_SCREEN_WIDTH="${NEXTUI_SCREEN_WIDTH:-1024}"
export NEXTUI_SCREEN_HEIGHT="${NEXTUI_SCREEN_HEIGHT:-768}"

mkdir -p "$NEXTREADING_BOOKS_PATH" "$NEXTREADING_CACHE_PATH" "$NEXTREADING_SAVES_PATH"

if [ -x "$APP_ROOT/nextreading" ]; then
    exec "$APP_ROOT/nextreading" --nextui "$@"
fi

echo "RetroRead binary not found: $APP_ROOT/nextreading" >&2
exit 1
